version: '3.3'

services:
  app:
    build:
      context: .
    ports:
      - 5001:80
    networks:
      - dashpag-net
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root

    volumes:
      - dbdata:/var/lib/mysql
      - ./.docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - dashpag-net

volumes:
  dbdata:

networks:
  dashpag-net:
    driver: bridge
  
