FROM mcr.microsoft.com/dotnet/core/sdk:2.1

ENV WAIT_VERSION 2.7.2
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/$WAIT_VERSION/wait /wait
RUN chmod +x /wait

COPY ./.docker/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

WORKDIR /app

COPY sonmarket.csproj .
RUN dotnet restore

COPY . .
EXPOSE 5000/TCP