version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: sh -c "/wait && /entrypoint.sh"
    environment:
      - WAIT_HOSTS=db:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=20
      - WAIT_HOST_CONNECT_TIMEOUT=20
    ports:
      - 80:5000
    depends_on:
      - db
    networks:
      - dashpag-net
    

  db:
    image: mysql:5.7
    environment:
      - MYSQL_USER=dashpag
      - MYSQL_PASSWORD=dashpag
      - MYSQL_ROOT_PASSWORD=root

    volumes:
      - ./.docker/dbdata:/var/lib/mysql
      - ./.docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - dashpag-net
  

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.6.4-1
    container_name: app-dev-phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_USER: dashpag
      MYSQL_PASSWORD: dashpag
    ports:
      - "8000:80"
    depends_on:
      - db
    networks:
      - dashpag-net
  

networks: 
  dashpag-net:
    driver: bridge
